In [ ]:
#The purpose of this exercise is to classify irises as steosa, versicolour, virginica based on the columns sepal length, sepal width, petal width, and
#petal length in the iris dataset from sklearn library and then we'll evaluate the performance of each of the models using K-fold cross validation
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier #import random forest classifier
import numpy as np

In [ ]:
irises = load_iris()
digits = load_digits()

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [ ]:
lr = LogisticRegression()#load a logistic regression model
lr.fit(x_train, y_train)#train the logistic regression model on digits dataset
lr.score(x_test, y_test)#returns mean accuracy of logistic regression model on test data

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [ ]:
svm = SVC()#load a support vector machine
svm.fit(x_train, y_train)#train the support vector machine on the digits dataset
svm.score(x_test, y_test)#returns mean accuracy of support vector machine on test data

0.9814814814814815

In [ ]:
rf = RandomForestClassifier()#load a random forest
rf.fit(x_train, y_train)#train the random forest on the digits dataset
rf.score(x_test, y_test)#returns mean accuracy of random forest on test data

0.9703703703703703

In [ ]:
lr_scores = cross_val_score(LogisticRegression(), irises.data, irises.target)#evaluate logistic regression model trained on iris data using cross_validation
lr_scores

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [ ]:
np.average(lr_scores)

0.9733333333333334

In [ ]:
dt_scores = cross_val_score(DecisionTreeClassifier(), irises.data, irises.target)#evaluate decision tree classifier trained on iris data using cross validation
dt_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [ ]:
np.average(dt_scores)

0.9600000000000002

In [ ]:
svm_scores = cross_val_score(SVC(), irises.data, irises.target)#evaluate support vector machine trained on iris data using cross validation
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [ ]:
np.average(svm_scores)

0.9666666666666666

In [ ]:
rf_scores = cross_val_score(RandomForestClassifier(n_estimators=40), irises.data, irises.target)#evaluate random forest trained on iris data using cross validation
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [ ]:
np.average(rf_scores)

0.96